services:

    # factories
    hevinci.form.scale:
        factory_method: create
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: ["@hevinci.form_type.scale", "@hevinci.entity.scale"]

    # entities
    hevinci.entity.scale:
        class: HeVinci\CompetencyBundle\Entity\Scale
        public: false;