language: php
php:
  - "5.4"
env:
  - DB=mysql
mysql:
  adapter: mysql2
  database: claroline_test
  username: travis
  encoding: utf8
before_script:
  - cd ..
  - ls

script: vendor/bin/phpunit -c phpunit_travis.xml
